### ISSUE TITLE
VRCSDKのanimationが良く警告に出るので無視できるanimation設定を追加したい

### ISSUE THREAD

**Issue by Narazaka** [gatosyocora/VRCAvatars3Validator#20]
**Is your feature request related to a problem? Please describe.**

VRCSDK同梱のデフォルトのanimationにおいてあまり一般的でないパス設定がなされているものが存在し、常に警告で出てくる。

![image](https://user-images.githubusercontent.com/1712548/120072471-0c2d7100-c0cf-11eb-9e7e-bf124c4222e4.png)
![image](https://user-images.githubusercontent.com/1712548/120072619-a988a500-c0cf-11eb-83bc-86d58fd44ca8.png)

**Describe the solution you'd like**

できれば各ルールにユーザー指定のパラメーターを追加できるようにし、そこに無視するアニメーションファイルを追加したい。
またデフォルトで上記のVRCSDKデフォアニメは追加しておいて、ユーザー側でオーバーライドしたい。

rubocopやeslintなどの設定に近しい感じ。

**Describe alternatives you've considered**

固定での実装でもとりあえずはいい気はする。

**Additional context**

**Comment by gatosyocora** [comment]
@Narazaka こんな感じにしてみましたがどうでしょう

**Comment by Narazaka** [comment]
@gatosyocora 
どちらかというと特定ルールのみに関わる設定はRuleItemに任意のオプションが付けられるようにしたほうが拡張性は良さそう？と思ってこういう感じにしてみましたがいかがでしょうか
#28
#29

**Comment by Narazaka** [comment]
@gatosyocora 
いろいろいじってましたが固まりました

**Comment by gatosyocora** [comment]
#29 で対応
