### ISSUE TITLE
TestRuleTest.csのTypo

### ISSUE THREAD

**Issue by koyashiro** [gatosyocora/VRCAvatars3Validator#3]
https://github.com/gatosyocora/VRCAvatars3Validator/blob/6b26c87b78f66a7f8ac8011a02e8ea30b1756c4c/Editor/Tests/TestRuleTest.cs#L25

メソッド名が `ResuleTypeIsWarnning` となっている。
正しくは `ResultTypeIsWarnning` 。

**Comment by gatosyocora** [comment]
bd2277e50e33b4e806858524c1340959cec8fd97 で修正
